### ISSUE TITLE
Throwing errors

### ISSUE THREAD

**Issue by developer-farhan** [mehranshoqi/voice_message_player#1]
`class Screen3 extends StatelessWidget {
  const Screen3({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          SizedBox(
            height: 50,
            width: 50,
            child: VoiceMessage(
              audioSrc:
                  audioLinkFromFirebase,
              played: false, // to show played badge or not.
              me: false, // set message side.
              onPlay: () {}, // do somethin when voice played.
            ),
          ),
        ],
      ),
    );
  }
}`

======== Exception caught by widgets library =======================================================
The following LateError was thrown building _BodyBuilder:
LateInitializationError: Field 'width' has not been initialized.

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
Each child must be laid out exactly once.

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderErrorBox#a8387 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2789 pos 12: '!_needsLayout'

======== Exception caught by Flutter framework =====================================================
The following StateError was thrown while executing callbacks for FrameTiming:
Bad state: Future already completed

**Comment by mehranshoqi** [comment]
Hello, I think you have a late variable that you forgot to initialize. check this -> https://stackoverflow.com/questions/67040839/flutter-lateinitializationerror-field-name-has-not-been-initialized

**Comment by developer-farhan** [comment]
Could you please copy paste me a working widget so I can test it out since there is no example code  thanks

**Comment by mehranshoqi** [comment]
Hi, please upgrade your package to latest version!

Thanks for reporting! Have fun.
