### ISSUE TITLE
Multiple audio notes playing in parallel

### ISSUE THREAD

**Issue by hassan-zarya** [mehranshoqi/voice_message_player#15]
For example, If I have 3 audio notes, I play one and then play the second one without waiting for the first one to finish, they both gets played.
I can't find a way to cater it, can you help?

**Comment by Saifallak** [comment]
did you find a way?

**Comment by wh120** [comment]
same

**Comment by Shams-Mahmoud** [comment]
any updates???

**Comment by AliSamir070** [comment]
any solution ?
