### ISSUE TITLE
 Error code -20 when initializing AudioTrack. When adding new message in UI

### ISSUE THREAD

**Issue by rvharjinderbains** [mehranshoqi/voice_message_player#21]
E/android.media.AudioTrack(29513): Error code -20 when initializing AudioTrack.
E/MediaCodecAudioRenderer(29513): Audio sink error
E/MediaCodecAudioRenderer(29513):   com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(44100, 12, 90624)
E/MediaCodecAudioRenderer(29513):       at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2110)
E/MediaCodecAudioRenderer(29513):       at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:1070)
E/MediaCodecAudioRenderer(29513):       at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrackWithRetry(DefaultAudioSink.java:1049)
E/MediaCodecAudioRenderer(29513):       at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:846)
E/MediaCodecAudioRenderer(29513):       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:929)
E/MediaCodecAudioRenderer(29513):       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:703)
E/MediaCodecAudioRenderer(29513):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1894)
E/MediaCodecAudioRenderer(29513):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
E/MediaCodecAudioRenderer(29513):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
E/MediaCodecAudioRenderer(29513):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
E/MediaCodecAudioRenderer(29513):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/MediaCodecAudioRenderer(29513):       at android.os.Looper.loop(Looper.java:164)
E/MediaCodecAudioRenderer(29513):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(29513): Playback error

**Comment by igorfastronicorrea** [comment]
any idea about how fix this bug?

**Comment by RemonYounan** [comment]
Same issue still exist and it happens a lot, any fix or suggestion to other packages?
