### ISSUE TITLE
 This widget has been unmounted, so the State no longer has a context

### ISSUE THREAD

**Issue by blacknight9** [mehranshoqi/voice_message_player#22]
hey, i keep getting this error

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
#0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:951:9)
#1      State.context (package:flutter/src/widgets/framework.dart:957:6)
#2      SingleTickerProviderStateMixin._updateTickerModeNotifier (package:flutter/src/widgets/ticker_provider.dart:248:68)
#3      SingleTickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:200:5)
#4      new AnimationController (package:flutter/src/animation/animation_controller.dart:247:21)
#5      _VoiceMessageState._setDuration (package:voice_message_package/src/voice_message.dart:325:19)
<asynchronous suspension>
flutter: _setAnimationConfiguration 00:09.589
flutter: _setAnimationConfiguration 00:01.161

**Comment by Shams-Mahmoud** [comment]
same here

**Comment by mnazarim** [comment]
Yeah, I'm still getting this error.

**Comment by mehranshoqi** [comment]
Sorry for the late response, You can check the new version, and all issues are resolved.
